apiVersion: apps/v1
kind: Deployment
metadata:
  name: service01-deployment01
  labels:
    app: service01
spec:
  replicas: 1  # number of pods
  selector:
    matchLabels:
      app: service01
  template:
    metadata:
      labels:
        app: service01
    spec:
      containers:
      - name: service01
        image: dilshan7542/testnode:latest
        imagePullPolicy: Always 
